/*
 * Embedded bitmap font for the graphical BDS UI.
 *
 * Monospace 24x24 cells, 4-bit anti-aliased alpha (16 levels), two pixels
 * packed per byte, row-major.  Covers ASCII 0x20-0x7E plus every CJK
 * character used by the UI string table; characters outside the table are
 * rendered as a hollow placeholder box by the drawing code.
 *
 * Copyright (c) 2026, contributors to the canoe ABL tree.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __SUPER_FB_FONT_H__
#define __SUPER_FB_FONT_H__

#include <Uefi.h>

#define SFB_FONT_CELL_W             24
#define SFB_FONT_CELL_H             24
#define SFB_FONT_BYTES_PER_GLYPH    ((SFB_FONT_CELL_W * SFB_FONT_CELL_H) / 2)
#define SFB_FONT_MAX_ALPHA          15

typedef struct {
  CHAR16  Ch;       /* Unicode code point */
  UINT16  Offset;   /* byte offset into gSfbFontBitmap */
} SFB_FONT_GLYPH;

/* Generated by tools/gen_sfb_font/gen_sfb_font.ps1. */
extern CONST UINT8          gSfbFontBitmap[];
extern CONST UINTN          gSfbFontGlyphCount;
extern CONST SFB_FONT_GLYPH gSfbFontGlyphs[];

/*
 * Look up the glyph for Ch.  Returns TRUE and sets *Offset to the byte
 * offset in gSfbFontBitmap, or FALSE when the character has no glyph.
 */
BOOLEAN
SfbFontGetGlyph (IN CHAR16 Ch, OUT UINT16 *Offset);

#endif /* __SUPER_FB_FONT_H__ */
