/*
 * Embedded bitmap font for the graphical BDS UI.
 *
 * Proportional glyphs on a 32px-tall grid, 4-bit anti-aliased alpha (16
 * levels), two pixels packed per byte, row-major.  Every glyph keeps only
 * its ink width (always even) plus an advance, so Latin letters sit close
 * together while CJK characters stay near full width.  Covers the full
 * printable ASCII range plus every CJK character used by the UI string
 * table; characters outside the table are rendered as a hollow placeholder
 * box by the drawing code.
 *
 * Copyright (c) 2026, contributors to the canoe ABL tree.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __SUPER_FB_FONT_H__
#define __SUPER_FB_FONT_H__

#include <Uefi.h>

#define SFB_FONT_CELL_H             32
#define SFB_FONT_MAX_W              32
#define SFB_FONT_MAX_ALPHA          15

typedef struct {
  CHAR16  Ch;        /* Unicode code point */
  UINT16  Offset;    /* byte offset into gSfbFontBitmap */
  UINT8   Width;     /* glyph width in pixels (even) */
  UINT8   Advance;   /* pen advance in pixels (includes side padding) */
} SFB_FONT_GLYPH;

/* Generated by tools/gen_sfb_font/gen_sfb_font.ps1. */
extern CONST UINT8          gSfbFontBitmap[];
extern CONST UINTN          gSfbFontGlyphCount;
extern CONST SFB_FONT_GLYPH gSfbFontGlyphs[];

/*
 * Look up the glyph for Ch.  Returns TRUE and fills Offset/Width/Advance, or
 * FALSE when the character has no glyph.
 */
BOOLEAN
SfbFontGetGlyph (IN CHAR16 Ch,
                 OUT UINT16 *Offset,
                 OUT UINT8  *Width,
                 OUT UINT8  *Advance);

#endif /* __SUPER_FB_FONT_H__ */
